---
# aws: los módulos de AWS corren en el controlador y llaman a la API.
# campus: equipos Cisco gestionados por SSH (network_cli).
# FW-DC (Firepower) no está aquí: se gestiona desde su consola FMC.
all:
  children:
    aws:
      hosts:
        aws-us-east-1:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    campus:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_user: "{{ vault_network_user }}"
        ansible_password: "{{ vault_network_password }}"
      children:
        edge:
          vars: {ansible_network_os: cisco.ios.ios}
          hosts:
            r-edge-01: {ansible_host: 10.0.10.1}
            r-edge-02: {ansible_host: 10.0.10.2}
        core:
          vars: {ansible_network_os: cisco.ios.ios}
          hosts:
            sw-core: {ansible_host: 10.0.10.11}
        dc_leaf:
          vars: {ansible_network_os: cisco.nxos.nxos}
          hosts:
            leaf-dc: {ansible_host: 10.0.10.31}
